import 'package:vimeo_clone/config/constants.dart';

const String loginWithGoogleUrl = "${apiUrl}login/email";
const String loginWithPhoneUrl = "${apiUrl}login/phone";
const String registerUserUrl = "${apiUrl}register";
const String loginUserUrl = "${apiUrl}login";
const String userLogOutUrl = "${apiUrl}logout";
const String getCategoriesUrl = "${apiUrl}categories";
const String getVideoListAsCategoryUrl = "${apiUrl}category";
const String getAllVideoListUrl = "${apiUrl}videos";
const String getVideoUrl = "${apiUrl}video";
const String uploadVideoUrl = "${apiUrl}video";
const String getShortsListUrl = "${apiUrl}shorts";
const String getSubscribedChannelListUrl = "${apiUrl}subscriptions";
const String subscribeChannelUrl = "${apiUrl}subscribe/";
const String unsubscribeChannelUrl = "${apiUrl}unsubscribe/";
const String getUserHistoryUrl = "${apiUrl}watched-videos";
const String getUserPlaylistUrl = "${apiUrl}playlists";
const String createPlaylistUrl = "${apiUrl}playlists";
const String getSearchDataUrl = "${apiUrl}search";
const String showSinglePlaylistUrl = "${apiUrl}playlists/";
const String getSearchSuggestionUrl = "${apiUrl}search-suggestions";
const String likeCommentUrl = "${apiUrl}comments/";
const String editChannelUrl = "${apiUrl}channels/";
